const seeds = [
  {
    uid: '1',
    username: 'Alicia',
    email: 'alicia@gmail.com',
    user_languages: ['Java'],
    rating_total: 0,
    rating_count: 0,
    needHelp: true,
  },
  {
    uid: '2',
    username: 'Ferdinand',
    email: 'ferdinand@gmail.com',
    user_languages: ['PHP', 'Javascript', 'Java', 'React'],
    rating_total: 5,
    rating_count: 1,
    needHelp: true,
  },
  {
    uid: '3',
    username: 'Tekraj',
    email: 'tekraj@gmail.com',
    user_languages: ['React', 'Angular'],
    rating_total: 0,
    rating_count: 0,
    needHelp: true,
  },
  {
    uid: '4',
    username: 'Raymond',
    email: 'raymond@gmail.com',
    user_languages: [],
    rating_total: 0,
    rating_count: 0,
    needHelp: false,
  },
  {
    uid: '5',
    username: 'Robert',
    email: 'robert@gmail.com',
    user_languages: ['Java'],
    rating_total: 0,
    rating_count: 0,
    needHelp: true,
    help_request: {
      title: 'Why do bees sting?',
      description: 'Stinging bees. Please help.',
      hr_languages: ['Javascript', 'PHP'],
    },
  },
  {
    uid: '6',
    username: 'Tekraj',
    email: 'tekraj3@gmail.com',
    user_languages: ['Java'],
    rating_total: 0,
    rating_count: 0,
    needHelp: true,
    help_request: {
      title: 'How to console.log',
      description: "Why can't I console.log",
      hr_languages: ['CSS', 'Javascript'],
    },
  },
];

export default seeds;
